### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by sitolam** [redyf/nixdots#3]
I installed nixos and hyprland on my laptop. Then I followed your instructions to install your configuration. When I tried to run `sudo nixos-rebuild switch --flake .#laptop` I get an error (see image). I hope you can help me.
![20230827_18h54m52s_grim](https://github.com/redyf/nixdots/assets/79202140/9d302cda-0831-4b2f-bf55-eb963cc89669)

**Comment by redyf** [comment]
That's not an issue on the config but rather from where it's being downloaded. I have no control over that.

**Comment by sitolam** [comment]
Do you know how I can fix it I live in Europe.

**Comment by redyf** [comment]
Honestly I'm quite unsure about why it's not working for you, does it happen in other parts of the installation or just hyprland?
