### ISSUE TITLE
Add fstrim

### ISSUE THREAD

**Issue by patrulhasirius** [redyf/nixdots#74]
I noticed that this config does not have services.fstrim.enable = true, I don't know if it's intended but if it's being used on an ssd it's would be a good performance boost.

I would like to create the PR but I already have a fork of this repository and github does not seem to allow me to create another(?).

**Comment by redyf** [comment]
Thanks for your suggestion, I'd like to give it a try first to see the performance boost but I believe it's better to just leave it to the user as not everyone uses an SSD.

**Comment by redyf** [comment]
Update: fstrim has been added 👍
