### ISSUE TITLE
Using a stable package

### ISSUE THREAD

**Issue by patrulhasirius** [redyf/nixdots#78]
I'm trying to add a specific stable package to the config but I'm a bit confused as to how to fix the structure to make it available for home-manager.

I think I need something like:

` #flake.nix
inputs = {
    nixpkgs-stable.url = "github:nixos/nixpkgs/nixos-23.11";
};
outputs = {
    nixpkgs-stable,
};`

And then importing in misc/default.nix with:

`home.packages = with pkgs; [
 ...
] ++ [
    pkgs-stable.lutris
]`

But I'm not sure how to generate pkgs-stable from nixpkgs-stable, from what I could grasp this is being done to the base nixpkgs in:

`pkgs = nixpkgsFor.${system};`

**Comment by redyf** [comment]
I'll take a look at this, this is actually a pretty good question. I apologize for taking this long to reply, please let me know if you found something :+1:

**Comment by redyf** [comment]
I managed to install a specific package from stable by doing this:

1- Add nixpkgs-stable to your inputs and outputs.
```nix
nixpkgs-stable.url = "github:nixos/nixpkgs/nixos-24.05";
``` 

2- Create a variable for importing nixpkgs-stable, I placed it below nixpkgsFor but it's up to you.

```nix
# Stable Nixpkgs instantiated for supported system types.
nixpkgsStableFor = forAllSystems (system: import nixpkgs-stable {inherit system;});
```

3- Add nixpkgs-stable to extraSpecialArgs in your home-manager modules:
```nix
          modules = [
            ./hosts/redyf/configuration.nix
            home-manager.nixosModules.home-manager
            {
              home-manager = {
                useUserPackages = true;
                useGlobalPkgs = false;
                extraSpecialArgs = {inherit inputs disko nixpkgs-stable;};
                users.redyf = ./home/redyf/home.nix;
                backupFileExtension = "backup";
              };
            }
```
4- Create a nix module to install the package you want (you can do it within your flake but I'm going with the module).
```nix
{nixpkgs-stable,...}: {   
    home.packages = [
      nixpkgs-stable.legacyPackages.x86_64-linux.cargo
    ];
}
```

![image](https://github.com/user-attachments/assets/51ce265b-be4b-4d59-9760-c30de364d5bc)
![image](https://github.com/user-attachments/assets/e6a93b3c-354d-4a1e-b841-4c38200455f2)

As you can see, the version matches the stable branch.
