### ISSUE TITLE
Question about dotfiles

### ISSUE THREAD

**Issue by Balssh** [redyf/nixdots#8]
Hi there, I'm just starting to learn NixOS and tried to recreate your dots. I got some basic setup but what I don't exactly understand is how are dotfiles in ~/.config managed? For example I see in your hyprland conf you execute scripts from ~/.config/hypr/scripts. Should I symlink them from /etc/nixos/ etc?

**Comment by IogaMaster** [comment]
[home-manager](https://github.com/nix-community/home-manager) creates and symlinks home configs and other home files from `/nix/store/...`
