### ISSUE TITLE
Why did you give up on `floorp` over `firefox`

### ISSUE THREAD

**Issue by caniko** [redyf/nixdots#98]
Noticed that floorp is in [here](https://github.com/redyf/nixdots/blob/main/home/apps/firefox/default.nix); however, it is commented out.

Not sure if this is relevant: https://github.com/nix-community/home-manager/pull/5128

**Comment by redyf** [comment]
No specific reason actually, I just wanted to switch to firefox. I left floorp commented there just in case I want to try to it again in the future.

**Comment by caniko** [comment]
I see! Thanks 😁
