### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Evren-os** [redyf/nixdots#99]
All steps were done perfectly. But the last command "nixos-install --flake .#redyf" gives error 

Error is : flake 'git+file///mnt/etc/nixos' doesn't provide attribute 'packages.x86_64-linux.nixConfigurations. "redyf" . config.system ........,............... so on

**Comment by redyf** [comment]
That's completely my fault, I forgot to update the readme about it. It should be "desktop" instead of "redyf".
```nixos-install --flake .#desktop```should work

**Comment by Evren-os** [comment]
> That's completely my fault, I forgot to update the readme about it. It should be "desktop" instead of "redyf". `nixos-install --flake .#desktop`should work

Ah working, I tried 7 times from morning , i thought nerd me did something wrong. Anyway thanks a lot. Let's if it completes or not

**Comment by Evren-os** [comment]
Another error, cannot find git revision 'eec.......' in refs/heads/main of repository 'ssh://git@github.com/ghostty-org/ghostty' Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit

**Comment by redyf** [comment]
That error happens because ghostty terminal is not public yet, so you can just comment those lines in the flake
